version: '3.9'

name: workout-tracker

services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=workout_tracker
      - MONGO_INITDB_ROOT_PASSWORD=!S3cr3t!